version: '3.4'

services:
  nginx:
    image: nginx:latest  

  microservicesample-rabitmq:
    image: rabbitmq:management

  microservicesample-postgres:
    image: postgres:${POSTGRES_VERSION} 

  microservicesample-contacts-api:
    image: ${DOCKER:-microservicesample}/contacts.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/services/Contacts/MicroserviceSample.Services.Contacts.API/Dockerfile

  microservicesample-reports-api:
    image: ${DOCKER:-microservicesample}/reports.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/services/reports/MicroserviceSample.Services.Reports.API/Dockerfile
       
